print("")
print ("It is easier to spin up a container for your developent environment")
print("-no need for installation/setup local development")
print("- take advantage of better infrastructure like SE2, Cloud or better local server")
print ("")
